/**
 * Daily runner for the local scheduled task: sync → scrape → commit → push.
 *
 * Point the scheduled task at `npm run daily` (or `node daily.js`) instead of
 * running scrape.js + git by hand. Why this exists: the old task committed and
 * pushed without pulling first, so once anything else was pushed to GitHub
 * (e.g. scraper fixes made from another machine) every daily push was rejected
 * as non-fast-forward — and nothing noticed. states.json went stale for weeks.
 *
 * This runner:
 *  - pulls (rebase + autostash) BEFORE scraping, so it always runs the latest
 *    scrape.js and starts from GitHub's states.json;
 *  - pushes, and on rejection pulls again and retries;
 *  - also pushes any earlier local commits a previous failed run left behind;
 *  - appends every run to daily.log and exits non-zero on any failure, so the
 *    scheduled task's "Last Run Result" shows it.
 */
const { execSync, spawnSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const LOG_FILE = path.join(ROOT, 'daily.log');

function log(msg) {
    const line = `[${new Date().toISOString()}] ${msg}`;
    console.log(line);
    fs.appendFileSync(LOG_FILE, line + '\n');
}

function git(args) {
    return execSync(`git ${args}`, { cwd: ROOT, encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] }).trim();
}

/** Files whose local, unpushed changes are safe to drop: states.json is
 * regenerated by the scrape that follows. */
const REGENERATED = new Set(['states.json']);

function sync() {
    git('fetch origin main');
    try {
        git('pull --rebase --autostash origin main');
        return;
    } catch (e) {
        try { git('rebase --abort'); } catch { /* not mid-rebase */ }
        try { git('stash pop'); } catch { /* nothing stashed */ }
        const unpushed = git('diff --name-only origin/main...HEAD').split('\n').filter(Boolean);
        const dirty = git('status --porcelain').split('\n').filter(Boolean).map((l) => l.slice(3));
        const onlyData = [...unpushed, ...dirty].every((f) => REGENERATED.has(f));
        if (!onlyData) {
            throw new Error(
                'Could not sync with GitHub and there are local changes besides states.json ' +
                `(${[...new Set([...unpushed, ...dirty])].join(', ')}). Resolve them by hand, then re-run.`,
            );
        }
        // Only stale scraped data is in the way — drop it and match GitHub.
        log('Sync conflict on states.json only — discarding stale local data and matching GitHub.');
        git('checkout -- states.json');
        git('reset --keep origin/main');
    }
}

function pushWithRetry(attempts = 3) {
    for (let i = 1; i <= attempts; i++) {
        try {
            git('push origin HEAD:main');
            return;
        } catch (e) {
            log(`Push attempt ${i} rejected: ${String(e.stderr || e.message).split('\n')[0]}`);
            if (i === attempts) throw e;
            sync();
        }
    }
}

function main() {
    log('--- daily run start ---');

    log('Syncing with GitHub...');
    sync();
    log(`At ${git('rev-parse --short HEAD')} (${git('log -1 --format=%s')})`);

    log('Scraping...');
    const res = spawnSync(process.execPath, [path.join(ROOT, 'scrape.js')], {
        cwd: ROOT,
        stdio: 'inherit',
        env: process.env,
    });
    if (res.status !== 0) throw new Error(`scrape.js exited with code ${res.status}`);

    if (git('status --porcelain -- states.json')) {
        git('add states.json');
        git(`commit -m "Update state data ${new Date().toISOString().slice(0, 10)}"`);
        log('states.json changed — committed.');
    } else {
        log('No data changes.');
    }

    const ahead = Number(git('rev-list --count origin/main..HEAD'));
    if (ahead > 0) {
        log(`Pushing ${ahead} commit(s)...`);
        pushWithRetry();
        log('Pushed.');
    }
    log('--- daily run OK ---');
}

try {
    main();
} catch (e) {
    log(`FAILED: ${String(e.stderr || e.message).trim()}`);
    process.exit(1);
}
